// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCv9M4JBJjDefy1Bimsj1xFpbWdmX7dvU',
    appId: '1:912059123598:web:636eaa7e3141170e4506df',
    messagingSenderId: '912059123598',
    projectId: 'demodesu-57c66',
    authDomain: 'demodesu-57c66.firebaseapp.com',
    storageBucket: 'demodesu-57c66.firebasestorage.app',
    measurementId: 'G-9SFYZX8REJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrlB8pE0F4Z2_J_PugEs71YrAXMl6sZ4k',
    appId: '1:912059123598:android:f9cca8d8298c6cc14506df',
    messagingSenderId: '912059123598',
    projectId: 'demodesu-57c66',
    storageBucket: 'demodesu-57c66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSboevCXj8AxmslEB7VSMnMf3H6DLX3ZY',
    appId: '1:912059123598:ios:0fab070f2df438a44506df',
    messagingSenderId: '912059123598',
    projectId: 'demodesu-57c66',
    storageBucket: 'demodesu-57c66.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSboevCXj8AxmslEB7VSMnMf3H6DLX3ZY',
    appId: '1:912059123598:ios:0fab070f2df438a44506df',
    messagingSenderId: '912059123598',
    projectId: 'demodesu-57c66',
    storageBucket: 'demodesu-57c66.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCv9M4JBJjDefy1Bimsj1xFpbWdmX7dvU',
    appId: '1:912059123598:web:fe81ac2464bb4e864506df',
    messagingSenderId: '912059123598',
    projectId: 'demodesu-57c66',
    authDomain: 'demodesu-57c66.firebaseapp.com',
    storageBucket: 'demodesu-57c66.firebasestorage.app',
    measurementId: 'G-BK3RPEJK6Z',
  );
}
